### ISSUE TITLE
Update to 1.4.3

### ISSUE THREAD

**Issue by PegaFox** [DarioDaF/TerrariaRandomWeapon#2]
I grabbed the source code and updated it for the newest version, if you're good with a pull request

**Comment by DarioDaF** [comment]
Sure I don't see a fork on your github, but feel free to create a pull request, I might add after a couple of improvoements that were left on the side to allow selecting 1.3 / 1.4 / and or the ability to add modded data (since the code itself is not really dependent on the version and items)

**Comment by PegaFox** [comment]
Just finished setting it up now
