### ISSUE TITLE
The website currently does not work 

### ISSUE THREAD

**Issue by Merchant415** [DarioDaF/TerrariaRandomWeapon#6]
none of the buttons work (get random weapon, next/previous stage, etc) however, the weapon list is able to be clicked on if it was already open

**Comment by Merchant415** [comment]
thanks for making the random weapon gen, its led to 100s of hours of fun with friends :)

**Comment by DarioDaF** [comment]
Thanks a lot for the feedback, I recently updated a bunch of stuff with the 1.4.4.7 data and totally missed the buttons not working! Now should be fixed, let me know if you have any other problem (saved state should carry along and not be reset), I'll wait for confirmation before closing the issue

**Comment by Merchant415** [comment]
yep, works great! thanks
