### ISSUE TITLE
Muramasa and Night's Edge are missing after defeating Skeletron

### ISSUE THREAD

**Issue by IssueTracer** [DarioDaF/TerrariaRandomWeapon#7]
As the title says those weapons are currently missing after defeating Skeletron. Also the title displays ''Terraira'' instead of Terraria

**Comment by DarioDaF** [comment]
Should be fixed with https://github.com/DarioDaF/TerrariaRandomWeapon/commit/fdb65d1a4b147348f5c73e1889513591a305848b

Let me know if it's ok (in case you still not see them could be necessary to refresh the page with F5)

**Comment by IssueTracer** [comment]
yeah it's now fixed , thanks
